// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs ,,const.go

package setupapi

const (
	DICD_GENERATE_ID = 0x1

	DICD_INHERIT_CLASSDRVS = 0x2

	DIOD_INHERIT_CLASSDRVS = 0x2

	DIGCF_PRESENT = 0x2

	DICS_FLAG_GLOBAL         = 0x1
	DICS_FLAG_CONFIGSPECIFIC = 0x2

	DIREG_DEV = 0x1
	DIREG_DRV = 0x2

	SPDRP_HARDWAREID                  = 0x1
	SPDRP_DEVICEDESC                  = 0x0
	SPDRP_FRIENDLYNAME                = 0xc
	SPDRP_ENUMERATOR_NAME             = 0x16
	SPDRP_PHYSICAL_DEVICE_OBJECT_NAME = 0xe
	SPDRP_BUSTYPEGUID                 = 0x13
	SPDRP_BUSNUMBER                   = 0x15
	SPDRP_CLASS                       = 0x7
	SPDRP_CLASSGUID                   = 0x8
	SPDRP_MFG                         = 0xb

	DIF_REGISTERDEVICE = 0x19

	DEVPROP_TYPEMOD_ARRAY = 0x1000
	DEVPROP_TYPEMOD_LIST  = 0x2000

	DEVPROP_TYPE_EMPTY                      = 0x0
	DEVPROP_TYPE_NULL                       = 0x1
	DEVPROP_TYPE_SBYTE                      = 0x2
	DEVPROP_TYPE_BYTE                       = 0x3
	DEVPROP_TYPE_INT16                      = 0x4
	DEVPROP_TYPE_UINT16                     = 0x5
	DEVPROP_TYPE_INT32                      = 0x6
	DEVPROP_TYPE_UINT32                     = 0x7
	DEVPROP_TYPE_INT64                      = 0x8
	DEVPROP_TYPE_UINT64                     = 0x9
	DEVPROP_TYPE_FLOAT                      = 0xa
	DEVPROP_TYPE_DOUBLE                     = 0xb
	DEVPROP_TYPE_DECIMAL                    = 0xc
	DEVPROP_TYPE_GUID                       = 0xd
	DEVPROP_TYPE_CURRENCY                   = 0xe
	DEVPROP_TYPE_DATE                       = 0xf
	DEVPROP_TYPE_FILETIME                   = 0x10
	DEVPROP_TYPE_BOOLEAN                    = 0x11
	DEVPROP_TYPE_STRING                     = 0x12
	DEVPROP_TYPE_STRING_LIST                = 0x2012
	DEVPROP_TYPE_SECURITY_DESCRIPTOR        = 0x13
	DEVPROP_TYPE_SECURITY_DESCRIPTOR_STRING = 0x14
	DEVPROP_TYPE_DEVPROPKEY                 = 0x15
	DEVPROP_TYPE_DEVPROPTYPE                = 0x16
	DEVPROP_TYPE_BINARY                     = 0x1003
	DEVPROP_TYPE_ERROR                      = 0x17
	DEVPROP_TYPE_NTSTATUS                   = 0x18
	DEVPROP_TYPE_STRING_INDIRECT            = 0x19
)
