// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ,,const.go

package syscall

const (
	ASYNC_LOW_LATENCY = 0x2000

	SER_RS485_ENABLED        = 0x1
	SER_RS485_RTS_ON_SEND    = 0x2
	SER_RS485_RTS_AFTER_SEND = 0x4
	SER_RS485_RX_DURING_TX   = 0x10
	SER_RS485_TERMINATE_BUS  = 0x20
)
