// mksyscall.pl -tags linux,386 syscall_linux.go
// Code generated by the command above; DO NOT EDIT.

// +build linux,386

package syscall

import "unsafe"
import "syscall"

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func IoctlSerial(fd uintptr, action int, s *Serial) (err error) {
	_, _, e1 := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd), uintptr(action), uintptr(unsafe.Pointer(s)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
