// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs linux/types.go

package syscall

type Serial struct {
	Type            int32
	Line            int32
	Port            uint32
	Irq             int32
	Flags           int32
	Xmit_fifo_size  int32
	Custom_divisor  int32
	Baud_base       int32
	Close_delay     uint16
	Io_type         int8
	Reserved_char   [1]int8
	Hub6            int32
	Closing_wait    uint16
	Closing_wait2   uint16
	Iomem_base      *uint8
	Iomem_reg_shift uint16
	Port_high       uint32
	Iomap_base      uint32
}
